site_name: Witch Plugin
site_description: Documentation for the Witch Plugin project
site_author: Witch Team
theme:
  name: material
  favicon: 'assets/branding/favicon.svg'
  palette:
    - scheme: slate
      primary: 'black'
      accent: 'cyan'
nav:
  - Spell List: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Usage: getting-started/usage.md
  - Development:
      - Core: development/core.md
      - Paper: development/paper.md
extra_css:
  - 'assets/css/extra.css'
extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/marked/marked.min.js'
  - 'assets/js/spell-loader.js'
